# Generated by Django 4.0 on 2022-01-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_staffs_user_type_students_user_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('is_general', 'Can add people to his company and see everything'), ('is_captain', 'Can add/edit/delete everything'), ('is_staff', 'Can add/edit/delete jobs'), ('is_programmer', 'Can do what he or she wants to do'))},
        ),
        migrations.RemoveField(
            model_name='adminhod',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='staffs',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='students',
            name='user_type',
        ),
    ]
